name: Main

on: [push]

jobs:
  vm-job:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Build and create DB
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup

    - name: Run Rspec tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bundle exec rspec -f d
