name: Main

on: [push]

jobs:
  vm-job:
    runs-on: ubuntu-16.04
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Build and create DB
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGPASSWORD: postgres
        PGDATABASE: postgres
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        # bin/rails db:setup
        RAILS_ENV=test rails db:create
        RAILS_ENV=test rails db:migrate

    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        PGPASSWORD: postgres
        PGDATABASE: postgres
        RAILS_ENV: test
      run: |
        bin/rails test
        # bundle exec rspec -f d

    # - name: Deploy new version
    #   run: |
    #     bundle exec cap production deploy
